name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - dev # Trigger the workflow on pushes to the 'dev' branch

permissions:
  id-token: write # Required for authenticating with AWS via OIDC
  contents: read

env:
  SOLUTION_NAME: Andishi.sln # Please confirm this is the correct solution file name
  PROJECT_PATH: Andishi.API/Andishi.API.csproj
  BUILD_CONFIG: Release
  EB_APPLICATION_NAME: andishi-demo # Replace with your Elastic Beanstalk application name
  EB_ENVIRONMENT_NAME: Andishi-demo-env-1 # Replace with your Elastic Beanstalk environment name
  REGION: eu-north-1 # Replace with your AWS region

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0' # Recommended to use LTS version unless preview features are needed

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_NAME }}

      - name: Publish application
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIG }} --output ./publish

      - name: Create deployment artifact
        run: |
          cd ./publish
          zip -r ../deploy_artifact.zip .

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          version_label: ${{ github.run_number }}
          region: ${{ env.REGION }}
          deployment_package: ./deploy_artifact.zip